theme = "hugo-theme-learn"
baseURL = "https://gamifying-refactoring.github.io/"

# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]

[Languages]
[Languages.en]
title = "Go beyond ilities"
weight = 1
languageName = "English"

[params]
custom_css = ["css/layout.css"]
disableLanguageSwitchingButton = true
disableBreadcrumb = true
description = "Gamifying Refactoring with an idea of going beyond ilities"
author = "Sarthak Makhija"

[[menu.shortcuts]]
name = "<i class='fa fa-male'></i>&nbsp;&nbsp;&nbsp;About Me"
url = "/about_me"
weight = 10

[[menu.shortcuts]]
name = "<i class='fab fa-github'></i> Code Repository"
url = "/code_repository"
weight = 20

[[menu.shortcuts]]
name = "<i class='fas fa-bullhorn'></i> Credits"
url = "/credits"
weight = 30